## Recommended to use UI instead of this yaml.
## This will not display the credentials in the UI, but it will merge it into the final "/.git-credentials/credentials" file that git will pickup.
## If you want this yaml to also display in UI, you need more annotations/labels: https://eclipse.dev/che/docs/stable/end-user-guide/using-a-git-provider-access-token/

kind: Secret
apiVersion: v1
metadata:
  name: git-credentials-secret
  labels:
    controller.devfile.io/git-credential: 'true'
    controller.devfile.io/watch-secret: 'true'
data:
  credentials: aHR0cHM6Ly9Zb3VyR2l0VXNlcm5hbWU6WW91clBBVFRva2VuQGdpdGh1Yi5jb20= ## base64 Github plaintext value example: https://YourGitUsername:YourPATToken@github.com
type: Opaque
